// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe3X5_w5NHlHxGFxVV1QGma6m-H3IuvWk',
    appId: '1:566563010383:web:7544c0a85985817b9b773a',
    messagingSenderId: '566563010383',
    projectId: 'fiverrclone-d00cd',
    authDomain: 'fiverrclone-d00cd.firebaseapp.com',
    storageBucket: 'fiverrclone-d00cd.appspot.com',
    measurementId: 'G-FSFF0PX2LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofC--G73XQtL8ZIe6T0ukGyk0fR-sLwA',
    appId: '1:566563010383:android:72d9d28be293c0729b773a',
    messagingSenderId: '566563010383',
    projectId: 'fiverrclone-d00cd',
    storageBucket: 'fiverrclone-d00cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7prbN2i7f8qERGBXyRd3ywq4Tf80NNo',
    appId: '1:566563010383:ios:c8671ef0cf8ce0389b773a',
    messagingSenderId: '566563010383',
    projectId: 'fiverrclone-d00cd',
    storageBucket: 'fiverrclone-d00cd.appspot.com',
    iosBundleId: 'com.example.f',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7prbN2i7f8qERGBXyRd3ywq4Tf80NNo',
    appId: '1:566563010383:ios:1d870cb158b1d9649b773a',
    messagingSenderId: '566563010383',
    projectId: 'fiverrclone-d00cd',
    storageBucket: 'fiverrclone-d00cd.appspot.com',
    iosBundleId: 'com.example.f.RunnerTests',
  );
}
